[package]
name = "phoenix-channel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secrecy = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
futures = "0.3.29"
base64 = "0.22.1"
serde = { version = "1.0.203", features = ["derive"] }
tracing = { workspace = true }
rand_core = "0.6.4"
url = "2.4.1"
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { workspace = true, features = ["net", "time"] }
backoff = "0.4.0"
uuid = { version = "1.7", default-features = false, features = ["std", "v4"] }
sha2 = "0.10.8"
hex = "0.4"
libc = "0.2"
socket-factory = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
hostname = "0.4.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
