[package]
name = "connlib-client-shared"
version = "0.1.0"
edition = "2021"

[features]
mock = ["connlib-shared/mock"]

[dependencies]
anyhow = "1.0.82"
tokio = { version = "1.38", default-features = false, features = ["sync", "rt"] }
secrecy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { version = "0.2.2" }
tracing-stackdriver = { version = "0.10.0" }
async-trait = { version = "0.1", default-features = false }
connlib-shared = { workspace = true }
firezone-tunnel = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
backoff = { workspace = true }
url = { version = "2.4.1", features = ["serde"] }
time = { version = "0.3.36", features = ["formatting"] }
bimap = "0.6"
ip_network = { version = "0.4", default-features = false }
phoenix-channel = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
tracing = { workspace = true, features = ["std", "attributes"] }

[dev-dependencies]
chrono = { workspace = true }
serde_json = { version = "1.0", features = ["std"] }
tokio = { version = "1.38", default-features = false, features = ["macros"] }

[lints]
workspace = true
