[package]
name = "firezone-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
secrecy = { workspace = true }
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive", "env"] }
bytecodec = "0.4.15"
futures = "0.3.29"
hex = "0.4.3"
rand = "0.8.5"
stun_codec = "0.3.4"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "time", "signal"] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "fmt"] }
tracing-stackdriver = { version = "0.10.0", features = ["opentelemetry"] }
tracing-opentelemetry = "0.23.0"
opentelemetry = { version = "0.22.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.15.0", features = ["metrics"] }
tracing-core = "0.1.31"
bytes = "1.4.0"
sha2 = "0.10.8"
base64 = "0.22.1"
once_cell = "1.17.1"
proptest = { version = "1", optional = true }
derive_more = { version = "0.99.18", features = ["from"] }
uuid = { version = "1.7.0", features = ["v4"] }
phoenix-channel = { path = "../phoenix-channel" }
url = "2.4.1"
serde = { version = "1.0.203", features = ["derive"] }
trackable = "1.3.0"
socket2 = "0.5.7"
backoff = "0.4"
http-health-check = { workspace = true }
mio = "0.8.11"
hex-display = "0.3.0"
socket-factory = { workspace = true }

[dev-dependencies]
difference = "2.0.0"
test-strategy = "0.3.1"
env_logger = "0.11.3"

[[test]]
name = "regression"
required-features = ["proptest"]

[lints]
workspace = true
