[package]
name = "firezone-gateway"
# mark:next-gateway-version
version = "1.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
async-trait = { version = "0.1", default-features = false }
backoff = { workspace = true }
boringtun = { workspace = true }
chrono = { workspace = true }
clap = "4.5.4"
connlib-shared = { workspace = true }
firezone-tunnel = { workspace = true }
futures = "0.3.29"
futures-bounded = { workspace = true }
firezone-bin-shared = { workspace = true }
phoenix-channel = { workspace = true }
secrecy = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread", "fs", "signal"] }
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect", "handshake", "rustls-tls-webpki-roots"] }
tracing = { workspace = true }
tracing-subscriber = "0.3.17"
url = { version = "2.4.1", default-features = false }
domain = { workspace = true }
uuid = { version = "1.7.0", features = ["v4"] }
ip_network = { version = "0.4", default-features = false }
dns-lookup = { workspace = true }
libc = { version = "0.2", default-features = false, features = ["std", "const-extern-fn", "extra_traits"] }
either = "1"
http-health-check = { workspace = true }
static_assertions = "1.1.0"
snownet = { workspace = true }
socket-factory = { workspace = true }

[dev-dependencies]
serde_json = { version = "1.0", default-features = false, features = ["std"] }

[lints]
workspace = true
